### ISSUE TITLE
Data type "|S12" does not unpacked when opening db specifying  

### ISSUE THREAD

**Issue by r-yamada1998** [ogawa-ros/necstdb#26]
Below works well
```python
>>>db = necstdb.opendb(data_path)
>>>obsmode = db.open_table("obsmode").read(astype="array")
```

However, 

```python
>>>db = necstdb.opendb(data_path)
>>>obsmode = db.open_table("obsmode").read(astype="df")

>>>print(obsmode["obs_mode"])
b' \x00\x00'
```

pandas is very useful when manipulating time x 1-dimensional data
Could you please fix the issue?@KaoruNishikawa

**Comment by KaoruNishikawa** [comment]
@r-yamada1998 
Thank you for reporting the counterintuitive behaviour.

This is not actually a bug of NECSTDB, but default behaviour on attempt to write string of non-uniform length, which is unsupported in NECSTDB, into single `table`.
Cutting out the pad byte (`\x00`) would result in partial support of non-uniform length string, but cannot support string data longer than allocated size to the field.

**We will modify the result via `table.recovered` property, for the reasons below.**

- To avoid inconsistency in data size and format character, between the output of `read` method and `header` property
  ```python
  >>> table = db.open_table("topic")
  >>> table.read(astype="tuple")[0]
  ("abc\x00\x00",)
  >>> table.header
  {'data': [{'key': 'string', 'format': '5s', 'size': 5}], ...}  # This is consistent
  ```
- Partial support of non-uniform length string can cause misuse of this database
- To avoid making a breaking change

**Comment by r-yamada1998** [comment]
@KaoruNishikawa 
I confirmed the modification policy. Keeping consistency in the return of `read` and the `header` property is important. 
My question is that,
to obtain the `\x00\x00`-dropped data frame, 
```python
>>> table = db.open_table("topic")
>>> table = table.recovered
>>> obsmode = table.read(astype="df") # \x00\x00 dropped
```

In contrast, to obtain the same format as the current implementation, 
```python
>>> table = db.open_table("topic")
>>> obsmode = table.read(astype="df") # \x00\x00 not dropped
```

Is it correct?

**Comment by KaoruNishikawa** [comment]
@r-yamada1998 
Yes, exactly!

**Comment by r-yamada1998** [comment]
@KaoruNishikawa 
Thank you,
Please modify using the `table.recovered` property.
